CREATE TYPE perfil_usuario AS ENUM ('bibliotecario', 'leitor');
CREATE TYPE status_emprestimo AS ENUM ('ativo', 'devolvido', 'atrasado');

CREATE TABLE usuarios (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil perfil_usuario NOT NULL
);

CREATE TABLE livros (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(150) NOT NULL,
    ano_publicacao INTEGER,
    quantidade_disponivel INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE emprestimos (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id INTEGER NOT NULL,
    leitor_id INTEGER NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_devolucao_prevista DATE NOT NULL,
    data_devolucao_real DATE,
    status status_emprestimo NOT NULL,

    CONSTRAINT fk_livro
        FOREIGN KEY (livro_id)
        REFERENCES livros(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_leitor
        FOREIGN KEY (leitor_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

INSERT INTO usuarios (nome, email, senha, perfil) VALUES
('Carlos Silva', 'carlos@biblioteca.com', '123456', 'bibliotecario'),
('Ana Souza', 'ana@email.com', '123456', 'leitor'),
('Joao Pereira', 'joao@email.com', '123456', 'leitor'),
('Mariana Lima', 'mariana@email.com', '123456', 'leitor');

INSERT INTO livros (titulo, autor, ano_publicacao, quantidade_disponivel) VALUES
('Dom Casmurro', 'Machado de Assis', 1899, 5),
('O Pequeno Principe', 'Antoine de Saint-Exupery', 1943, 3),
('1984', 'George Orwell', 1949, 4),
('Clean Code', 'Robert C. Martin', 2008, 2),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 1997, 6);

INSERT INTO emprestimos (
    livro_id,
    leitor_id,
    data_emprestimo,
    data_devolucao_prevista,
    data_devolucao_real,
    status
) VALUES
(1, 2, '2026-05-01', '2026-05-10', '2026-05-09', 'devolvido'),
(3, 3, '2026-05-15', '2026-05-25', NULL, 'ativo'),
(4, 4, '2026-05-05', '2026-05-12', NULL, 'atrasado');